package com.praxis.prax.conversation.domain;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * One thread of questions.
 *
 * Until now Prax kept a single in-memory `history` list: global, unscoped, and
 * lost on restart. That was survivable for a floating card that answers one
 * question. It is actively wrong for a workspace — two browser tabs shared one
 * history, so a question asked in one changed the answer given in the other.
 *
 * The plan called this the hidden cost of the workspace, and it is: nothing
 * about a transcript pane works properly without it.
 */
@Entity
@Table(name = "prax_conversation", indexes = {
        @Index(name = "idx_prax_conversation_user", columnList = "username, last_message_at")
})
@Getter @Setter @Builder @NoArgsConstructor @AllArgsConstructor
public class Conversation {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false, length = 64)
    private String username;

    /**
     * Taken from the first question rather than generated by the model.
     *
     * A title is a label, not a claim — but asking a 4B model to write one costs
     * a whole generation pass and can hallucinate a subject the conversation
     * never had.
     */
    @Column(length = 200)
    private String title;

    @CreationTimestamp
    @Column(name = "started_at", nullable = false, updatable = false)
    private OffsetDateTime startedAt;

    /** Sorting key for "most recent first". Updated on every exchange. */
    @Column(name = "last_message_at")
    private OffsetDateTime lastMessageAt;

    /** Longest sensible first question, before it stops being a title. */
    public static final int MAX_TITLE = 80;

    public static String titleFrom(String question) {
        if (question == null || question.isBlank()) return "New chat";
        String t = question.strip().replaceAll("\\s+", " ");
        return t.length() <= MAX_TITLE ? t : t.substring(0, MAX_TITLE - 1) + "…";
    }
}
