"""Writes config/grid_v1/<arm>.yaml for the 11 Phase 7 arms (PREREGISTRATION.md §3).

    python training/tools/make_grid_configs.py

One recipe, written once: the arms differ only in the base model, the R level
(or ablated R3) and, for one arm, the LoRA rank. Regenerating is idempotent, so
the committed files and this script cannot drift apart unnoticed.
"""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "config" / "grid_v1"

TARGETS = [  # both attention kinds of the hybrid, then the MLP (see dev_0p8b_phase6.yaml)
    "q_proj", "k_proj", "v_proj", "o_proj",
    "in_proj_qkv", "in_proj_z", "in_proj_b", "in_proj_a", "out_proj",
    "gate_proj", "up_proj", "down_proj",
]

ARMS = {
    # arm: (base, data folder, rank)
    "2b-r0": ("Qwen/Qwen3.5-2B", "data/phase6_v1/R0", 16),
    "2b-r1": ("Qwen/Qwen3.5-2B", "data/phase6_v1/R1", 16),
    "2b-r2": ("Qwen/Qwen3.5-2B", "data/phase6_v1/R2", 16),
    "2b-r3": ("Qwen/Qwen3.5-2B", "data/phase6_v1/R3", 16),
    "4b-r0": ("Qwen/Qwen3.5-4B", "data/phase6_v1/R0", 16),
    "4b-r3": ("Qwen/Qwen3.5-4B", "data/phase6_v1/R3", 16),
    "2b-r3-nocf": ("Qwen/Qwen3.5-2B", "data/phase7/ablations/nocf/R3", 16),
    "2b-r3-not": ("Qwen/Qwen3.5-2B", "data/phase7/ablations/not/R3", 16),
    "2b-r3-nodelta": ("Qwen/Qwen3.5-2B", "data/phase7/ablations/nodelta/R3", 16),
    "2b-r3-nod": ("Qwen/Qwen3.5-2B", "data/phase7/ablations/nod/R3", 16),
    "2b-r3-r32": ("Qwen/Qwen3.5-2B", "data/phase6_v1/R3", 32),
}
# Pilot and run order: the headline arm first, so the most important result
# exists earliest if the budget runs out (§10: missing arms are reported missing).
ORDER = ["2b-r3", "2b-r1", "2b-r0", "2b-r2", "4b-r3", "4b-r0",
         "2b-r3-nocf", "2b-r3-not", "2b-r3-nodelta", "2b-r3-nod", "2b-r3-r32"]


def config(arm: str) -> dict:
    base, data, rank = ARMS[arm]
    out = f"outputs/grid_v1/{arm}"
    return {
        "model": {"base": base, "revision": "main", "dtype": "bfloat16", "max_seq_length": 1536},
        # alpha = 2 x r keeps the update's scale fixed across the rank arm.
        "lora": {"r": rank, "alpha": 2 * rank, "dropout": 0.0, "target_modules": TARGETS},
        "train": {
            "epochs": 2,
            # Effective batch 8 (§3); 4 x 2 instead of the laptop's 1 x 8 only
            # because the rented card has the memory for it.
            "per_device_batch_size": 4,
            "gradient_accumulation_steps": 2,
            "learning_rate": 2.0e-4,
            "warmup_ratio": 0.05,
            "lr_scheduler_type": "cosine",
            "logging_steps": 10,
            "seed": 17,
            "gradient_checkpointing": True,
            "completion_only": True,
        },
        "data": {"train": f"{data}/train.jsonl", "val": f"{data}/val.jsonl"},
        "output": {
            "adapter_dir": f"{out}/lora",
            "merged_dir": f"{out}/merged",
            "gguf": f"{out}/praxis-grid-{arm}-q4_k_m.gguf",
            "ollama_model": f"praxis-grid-{arm}",
            "num_ctx": 3072,
        },
    }


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    header = "# Generated by training/tools/make_grid_configs.py; edit that, not this.\n"
    for arm in ORDER:
        (OUT / f"{arm}.yaml").write_text(header + yaml.safe_dump(config(arm), sort_keys=False), encoding="utf-8")
    (OUT / "ORDER").write_text("\n".join(ORDER) + "\n", encoding="utf-8")
    print(f"{len(ORDER)} configs -> {OUT}")


if __name__ == "__main__":
    main()
